logging.level.org.springframework=INFO
logging.level.root=ERROR
server.error.include-stacktrace=never
spring.profiles.active=demo
#spring.main.banner-mode=off
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=false

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.datasource.url=jdbc:h2:mem:mytestdb;DB_CLOSE_DELAY=-1